### ISSUE TITLE
Manually set node IP in config?

### ISSUE THREAD

**Issue by danny91** [craigwatson/bitcoind-status#15]
Hi, Im running the webserver on a different server but still the same external IP. I have tried using get IP from bitcoind however the field just remains blank.

Like this, Also MS doesnt show. and no links to bitnode ext.
![like this](https://cloud.githubusercontent.com/assets/16515882/12074166/10e5a5de-b13d-11e5-833f-3f7e0c7ccefc.PNG)

Is their a way to solve this? Thanks.

**Comment by craigwatson** [comment]
I haven't added any option to manually set a public IP address. Either of the automatic options should work for you.

Can you please post your `config.php` file?

**Comment by danny91** [comment]
Hi thanks for the reply sorry for taking a while to get back to you!

I have it up now http://electrumserv.noip.me however as you can see its still not showing MS. 

I should mention i am running it on windows (xampp) because thats what the node runs off.

Do you know if their is a way to show the uptime in windows on the page? :) Thanks!

This is my config.php http://pastebin.com/NWpRPMgd

**Comment by craigwatson** [comment]
Unfortunately all of my nodes are running on Linux (see links below), so I don't know any way of getting the bitcoind uptime on Windows, sorry. If you find out, you're welcome to post it or (even better) submit a pull request.

Can you confirm you've pulled the latest updates from GitHub? I've recently fixed an issue getting the Bitnodes latency, so that should work with the latest code.

My nodes:

https://thor.vikingserv.net
https://tyr.vikingserv.net
https://odin.vikingserv.net

**Comment by danny91** [comment]
It seems the recent update fixed it thanks! :)

I'm going to investigate how to show the uptime, ill let you know if i figure it out :P
