### ISSUE TITLE
feature request - update dynamically

### ISSUE THREAD

**Issue by rebroad** [craigwatson/bitcoind-status#29]
Would it be possible to have the display update dynamically? i.e. not have to refresh the page? Perhaps it could then update every second, if desired. (perhaps too much data for a WAN though).

**Comment by craigwatson** [comment]
Hi,

Apologies for taking just under two months to respond to this!

Sadly dynamic updates are beyond the scope of the script (let along my abilities, I'm a systems engineer by profession rather than a developer!).

The main concern is that it would be too many RPC calls for the Bitcoin daemon, if you imagine many people with open dynamic connections, it'd be possible to create hundreds of connections from the script.

If you require a dynamic feel, you can shorten the cache time to something more suitable like 2 or 3 minutes.

Hope that helps!
Craig
