### ISSUE TITLE
some displayed infos are wrong if web server and bitcoin node are not on same machine

### ISSUE THREAD

**Issue by marec2000** [craigwatson/bitcoind-status#34]
E.g. free disk space and uptime are not displayed correctly if web server resides on a different machine than bitcoin daemon. Currently free disk space and uptime of the web server is shown rather then those of the remote machine where bitcoin daemon is running. The IP of that machine might also be affected, but ip info seems to be missing in the getnetworkinfo localaddresses array so this could be another problem (maybe of the daemon itself - running 0.14.2).

Anyway, it's a good status page to have a look at when you want to know what's going on with your bitcoin node. 👍

**Comment by craigwatson** [comment]
Hi @marec2000 - thanks for the message, the disk space and uptime issues you mentioned are a feature rather than a bug :)

As far as I'm aware, there's no way for PHP to get the information from a remote system without relying on an elaborate setup using SSH, so that would most likely be beyond the scope of the script.

If necessary, you can switch off display of most things by using `config.php` :)
