### ISSUE TITLE
Node Height and Difficulty not displayed correctly

### ISSUE THREAD

**Issue by Boesboes** [craigwatson/bitcoind-status#48]
Since the update to support 0.16 node height and difficulty are displayed as 0.

**Comment by Boesboes** [comment]
Had some time to look at this problem. The cause is that some data is missing in the getnetworkinfo(). If getblockchaininfo() is appended all the information is present. Very new to coding so maybe some better way to do this. :)

```
diff functions.php functions.php.bak
55,57c55
<     $data_network = $bitcoin->getnetworkinfo();
<     $data_blockchain = $bitcoin->getblockchaininfo();
<     $data = array_merge($data_network, $data_blockchain);
---
>     $data = $bitcoin->getnetworkinfo();
```

**Comment by craigwatson** [comment]
Thanks for reporting this :)

**Comment by DemonRx** [comment]
Hi @craigwatson I'd like to request this issue re-opened because the status page doesn't handle "proof-of-work" and "proof-of-stake" values like some altcoins have. As is it only appears as *0* for Difficulty.

I've changed the following in my local copy to make it work by adding to functions.php:
```php
    // Get Difficulty
    $difficulty = $bitcoin->getdifficulty();
    $data['proof-of-stake'] = $difficulty['proof-of-stake'];
    $data['proof-of-work'] = $difficulty['proof-of-work'];
```
However, I would like this to be set up so in config.php we can select if this is a POS or POW coin so it automatically chooses the correct one.

If you could assist, please do, thank you !

**Comment by DemonRx** [comment]
So this is working for the setup in html/template.html:
```php
<?php if (isset($data['proof-of-work'])) { ?>
      <p class="stat"><span class="label">Difficulty:</span> <?php echo number_format($data['proof-of-work'],3);?> POW </p>
<?php } ?>
<?php if (isset($data['proof-of-stake'])) { ?>
      <p class="stat"><span class="label">Difficulty:</span> <?php echo number_format($data['proof-of-stake'],3); ?> POS </p>
<?php } ?>
```
And the result:

![image](https://user-images.githubusercontent.com/18432686/53891922-552e1200-3ff9-11e9-9956-c6ab8a7ea0cc.png)

**Comment by DemonRx** [comment]
Let me know if you have better method for this. thanks 

Also I couldn't get max_height working right, even so I changed the value in functions.php to my coin's explorer api (using iquidus explorer's api). still appears as (INF%) on the status page.
